#!/bin/bash
# Adaptation of nexus-fork/tools/build_unified_cubins_local.sh to this machine.
# Original assumes ~/rt_build/{nexus-migrate,vortx-unified} + miniconda CUDA;
# here the repos are /workspace/{nexus-fork,vortx-unified} and CUDA is system.
set -eo pipefail
TOOL=$HOME/.rustup/toolchains/nightly-2026-04-03-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin
LIBDEV=/usr/local/cuda/nvvm/libdevice/libdevice.10.bc
PTXAS=/usr/local/cuda/bin/ptxas
BACKEND=/workspace/cuda-oxide/crates/rustc-codegen-cuda/target/debug/librustc_codegen_cuda.so
export CUDA_OXIDE_PTX_DIR=/workspace/rt_build/nexus_ptx
mkdir -p "$CUDA_OXIDE_PTX_DIR"
export PATH=$HOME/.cargo/bin:$PATH

build_one () { # $1 workspace dir, $2 package, $3 features, $4 ll name, $5 crate src dir
  cd "$1"
  LL=$CUDA_OXIDE_PTX_DIR/$4.ll
  rm -f "$LL"
  find "$5" -name '*.rs' -exec touch {} +
  CARGO_INCREMENTAL=0 RUSTFLAGS="-Z codegen-backend=$BACKEND -Zalways-encode-mir -Zmir-enable-passes=-JumpThreading" \
    cargo +nightly-2026-04-03 build -p "$2" --release \
    --no-default-features --features "$3" \
    --target nvptx64-nvidia-cuda -Z build-std=core
  [ -s "$LL" ] || { echo "FATAL: $LL not regenerated by the shader build"; exit 1; }
  echo "ll: $(grep -c '^define' "$LL") defines"
  grep -q ') #0 {' "$LL" || { echo "FATAL: $LL lacks function-level convergent attrs"; exit 1; }
  "$TOOL"/llvm-as "$LL" -o /tmp/u.bc
  "$TOOL"/llvm-link /tmp/u.bc "$LIBDEV" -o /tmp/u_linked.bc
  "$TOOL"/opt -passes="internalize,globaldce,default<O3>" /tmp/u_linked.bc -o /tmp/u_pruned.bc
  "$TOOL"/llc -mcpu=sm_120 -O3 -fp-contract=fast /tmp/u_pruned.bc -o /tmp/u.ptx
  "$PTXAS" -arch=sm_120 -O3 /tmp/u.ptx -o "$CUDA_OXIDE_PTX_DIR/$4.cubin"
  ls -la "$CUDA_OXIDE_PTX_DIR/$4.cubin"
}

build_one /workspace/nexus-fork   nexus_rbd_shaders3d "cuda-oxide dim3 unsafe_remove_boundchecks" nexus_rbd_shaders3d /workspace/nexus-fork/src_rbd_shaders
build_one /workspace/vortx-unified vortx-shaders      "cuda-oxide"                                vortx_shaders       /workspace/vortx-unified/vortx-shaders/src
echo DONE
